#!/bin/bash
# Test deployment script for zig-to-yul
# This script compiles a Zig contract to Yul, then to EVM bytecode,
# deploys it to a local Anvil testnet, and tests calling it.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
COMPILER="$PROJECT_DIR/zig-out/bin/zig_to_yul"
SOLC="${SOLC:-$HOME/.local/bin/solc}"
ANVIL="${ANVIL:-$HOME/.foundry/bin/anvil}"
CAST="${CAST:-$HOME/.foundry/bin/cast}"

# Test contract
TEST_CONTRACT="${1:-$PROJECT_DIR/examples/simple.zig}"
OUTPUT_DIR="/tmp/zig-to-yul-test"

# Anvil default accounts
PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
DEPLOYER="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Zig-to-Yul Deployment Test${NC}"
echo -e "${GREEN}========================================${NC}"

# Cleanup and setup
mkdir -p "$OUTPUT_DIR"
rm -f "$OUTPUT_DIR"/*

# Check if compiler exists
if [ ! -f "$COMPILER" ]; then
    echo -e "${YELLOW}Building compiler...${NC}"
    cd "$PROJECT_DIR" && zig build
fi

# Step 1: Compile Zig to Yul
echo -e "\n${YELLOW}Step 1: Compiling Zig to Yul...${NC}"
echo -e "${BLUE}Input: $TEST_CONTRACT${NC}"
"$COMPILER" compile "$TEST_CONTRACT" -o "$OUTPUT_DIR/contract.yul"
echo -e "${GREEN}✓ Generated Yul code${NC}"
echo -e "${BLUE}--- Yul Output ---${NC}"
cat "$OUTPUT_DIR/contract.yul"
echo -e "${BLUE}--- End Yul ---${NC}"

# Step 2: Compile Yul to EVM bytecode
echo -e "\n${YELLOW}Step 2: Compiling Yul to EVM bytecode...${NC}"
"$SOLC" --strict-assembly "$OUTPUT_DIR/contract.yul" --bin > "$OUTPUT_DIR/solc_output.txt" 2>&1 || {
    echo -e "${RED}solc compilation failed:${NC}"
    cat "$OUTPUT_DIR/solc_output.txt"
    exit 1
}

# Extract bytecode from solc output - look for "Binary representation:" line
BYTECODE=$(grep -A1 "Binary representation:" "$OUTPUT_DIR/solc_output.txt" | tail -1 | tr -d '[:space:]')
if [ -z "$BYTECODE" ]; then
    # Fallback: look for "Binary:" line
    BYTECODE=$(grep -A1 "Binary:" "$OUTPUT_DIR/solc_output.txt" | tail -1 | tr -d '[:space:]')
fi
echo "0x$BYTECODE" > "$OUTPUT_DIR/bytecode.txt"
echo -e "${GREEN}✓ Generated bytecode (${#BYTECODE} hex chars)${NC}"
echo -e "${BLUE}Bytecode: 0x${BYTECODE}${NC}"

if [ -z "$BYTECODE" ] || [ "$BYTECODE" = "0x" ]; then
    echo -e "${RED}Error: Empty bytecode generated${NC}"
    cat "$OUTPUT_DIR/solc_output.txt"
    exit 1
fi

# Step 3: Start Anvil (if not running)
echo -e "\n${YELLOW}Step 3: Starting local Anvil testnet...${NC}"
# Kill any existing Anvil
pkill -f "anvil.*8545" 2>/dev/null || true
sleep 1

"$ANVIL" --host 127.0.0.1 --port 8545 > "$OUTPUT_DIR/anvil.log" 2>&1 &
ANVIL_PID=$!
echo "Anvil PID: $ANVIL_PID"
sleep 3

# Check if Anvil started successfully
if ! kill -0 $ANVIL_PID 2>/dev/null; then
    echo -e "${RED}Failed to start Anvil${NC}"
    cat "$OUTPUT_DIR/anvil.log"
    exit 1
fi
echo -e "${GREEN}✓ Anvil started on http://127.0.0.1:8545${NC}"

# Step 4: Deploy contract
echo -e "\n${YELLOW}Step 4: Deploying contract...${NC}"
DEPLOY_OUTPUT=$("$CAST" send --private-key "$PRIVATE_KEY" \
    --rpc-url http://127.0.0.1:8545 \
    --create "0x$BYTECODE" \
    --json 2>&1)

echo "$DEPLOY_OUTPUT" > "$OUTPUT_DIR/deploy_output.json"

# Extract contract address from JSON output
CONTRACT_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep -oE '"contractAddress":"0x[a-fA-F0-9]{40}"' | cut -d'"' -f4)

if [ -z "$CONTRACT_ADDRESS" ]; then
    echo -e "${RED}Failed to get contract address from deployment${NC}"
    echo "$DEPLOY_OUTPUT"
    CONTRACT_ADDRESS=$("$CAST" compute-address "$DEPLOYER" --nonce 0 2>/dev/null | grep -oE '0x[a-fA-F0-9]{40}' | head -1)
fi

echo -e "${GREEN}✓ Contract deployed at: $CONTRACT_ADDRESS${NC}"

# Step 5: Get contract code
echo -e "\n${YELLOW}Step 5: Verifying deployment...${NC}"
sleep 1
CODE=$("$CAST" code "$CONTRACT_ADDRESS" --rpc-url http://127.0.0.1:8545 2>/dev/null)
echo -e "${BLUE}Deployed code: $CODE${NC}"

if [ "$CODE" != "0x" ] && [ -n "$CODE" ]; then
    echo -e "${GREEN}✓ Contract code verified (${#CODE} chars)${NC}"
else
    echo -e "${RED}✗ No code at address (contract may have self-destructed or deployment failed)${NC}"
fi

# Step 6: Test call (if contract has functions)
echo -e "\n${YELLOW}Step 6: Testing contract interaction...${NC}"

# Get balance of deployer
BALANCE=$("$CAST" balance "$DEPLOYER" --rpc-url http://127.0.0.1:8545)
echo -e "${GREEN}✓ Deployer balance: $BALANCE wei${NC}"

# Try calling the contract with empty calldata (should revert for our simple contract)
echo -e "${BLUE}Calling contract with empty calldata...${NC}"
CALL_RESULT=$("$CAST" call "$CONTRACT_ADDRESS" "" --rpc-url http://127.0.0.1:8545 2>&1 || echo "reverted")
echo -e "${BLUE}Call result: $CALL_RESULT${NC}"

# Summary
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}  Test Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "Contract Address: ${BLUE}$CONTRACT_ADDRESS${NC}"
echo -e "Yul Code: ${BLUE}$OUTPUT_DIR/contract.yul${NC}"
echo -e "Bytecode: ${BLUE}$OUTPUT_DIR/bytecode.txt${NC}"
echo -e "Deployed Code: ${BLUE}$CODE${NC}"
echo -e "\n${YELLOW}To interact with the contract:${NC}"
echo -e "  cast call $CONTRACT_ADDRESS 'function_name()' --rpc-url http://127.0.0.1:8545"

# Cleanup
echo -e "\n${YELLOW}Stopping Anvil...${NC}"
kill $ANVIL_PID 2>/dev/null || true

echo -e "${GREEN}Done!${NC}"
